---
- name: Restore webserver Index file
  hosts: rhel1
# Watches the file and runs a playbook if it's deleted.
  sources:
    - name: watch-inde
      ansible.eda.file_watch:
        path: /var/www/html/index.html
        recursive: false
        
  rules:
    - name: Restore index.html if deleted
      condition: event.event_type == "deleted" and event.path == "/var/www/html/index.html"
      actions:
        - run_playbook:
            name: restore-index.yml
