---
- name: Restore webserver Index file
  hosts: rhel1
# Watches the file and runs a playbook if it's deleted.
  sources:
    - name: watch-index
      ansible.eda.file_watch:
        path: /var/www/html/index.html
        recursive: false
        
  rules:
    - name: Restore index.html if deleted
      condition: event.event_type == "deleted" and event.src_path == "/var/www/html/index.html"
      actions:
        - run_job_template:
            name: Restore Index File
            organization: Default
